### PR TITLE
fixed size of initialiser for dropout layers

### PR DESCRIPTION
**Pull request by rmeertens**
WIthout this fix the notebook does not work :(

### CODE REVIEW

**Comment by pkmital** [comment]
TY!

**Comment by rmeertens** [comment]
Well, thank you for making the course ;)
Also, thought you might be interested in this project I made after following your course and reading some papers: https://github.com/rmeertens/GameboyCameraPhotorealistic/blob/master/photoGameboyCamera.ipynb

**Comment by rmeertens** [comment]
Also: I saw you were working on new courses. If you want to discuss ideas or need somebody to test them, I would be happy to help you!

**Comment by pkmital** [comment]
@rmeertens Sorry I didn't get notifications for this!  Sounds great!  Please contact me at parag@kadenze.com

**Pull request merged**
